# Generated by Django 3.2.6 on 2021-08-18 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20210818_1115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='create',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='create',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='create',
            new_name='created',
        ),
    ]
