# Generated by Django 3.1.4 on 2021-09-19 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20210918_0521'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('-vote_ratio', '-vote_total', 'title')},
        ),
    ]
